Repository kuoss/venti, pull requests merged in 2023-04, with the labels that each got.

#14 13 main reconstruction
  .github/workflows/ci.yml
  docs/go-licenses.csv
  go.mod
  go.sum
  main.go
  pkg/alert/alert.go
  pkg/auth/user.go
  pkg/configuration/config.go
  pkg/configuration/config_test.go
  pkg/handleSPA.go
  pkg/handler/alert.go
  pkg/handler/auth.go
  pkg/handler/config.go
  pkg/handler/dashboard.go
  pkg/handler/datasources.go
  pkg/handler/lethe.go
  pkg/handler/prometheus.go
  pkg/query/querier.go
  pkg/query/query.go
  pkg/server.go
  pkg/store/alertrulestore.go
  pkg/store/dashboard.go
  pkg/store/dashboardStore.go
  pkg/store/datasource.go
  pkg/store/datasourceStore.go
  pkg/store/datasourceStore_test.go
  pkg/store/store.go
  pkg/store/userStore.go
  server/auth.go
  server/config.go
  server/config_test.go
  server/datasourceStore.go
  server/datasourceStore_test.go
  server/db.go
  server/httpClient.go
  server/httpQuery.go
  server/routes_api_alerts.go
  server/routes_api_config.go
  server/routes_api_datasources.go
  server/routes_api_lethe.go
  server/routes_api_prometheus.go
  server/server.go
  server/types.go
Labels: size/XXL

#18 fix go test all packages
  .github/workflows/ci.yml
Labels: size/XS

#20 bugfix loading config & test code
  .github/workflows/ci.yml
  Makefile
  etc/.gitignore
  etc/datasources.yaml
  pkg/configuration/config.go
  pkg/configuration/config_test.go
  pkg/handler/alert.go
  pkg/handler/dashboard.go
  pkg/server.go
  pkg/store/alertRuleStore.go
  pkg/store/alertRuleStore_test.go
  pkg/store/alertrulestore.go
  pkg/store/userStore.go
  scripts/checks.sh
  scripts/test-cover.sh
Labels: bug, size/L

#24 go filename convention
  pkg/handle_spa.go
  pkg/store/alert_rule_store.go
  pkg/store/alert_rule_store_test.go
  pkg/store/dashboard_store.go
  pkg/store/datasource.go
  pkg/store/datasource_store.go
  pkg/store/datasource_store_test.go
  pkg/store/user_store.go
Labels: refactoring, size/XS

#28 datasource store logic + test code
  pkg/configuration/config.go
  pkg/configuration/config_test.go
  pkg/handler/datasources.go
  pkg/server.go
  pkg/store/alert_rule_store_test.go
  pkg/store/datasource_store.go
  pkg/store/datasource_store_test.go
Labels: bug, enhancement, size/L

#31 model package
  .github/workflows/ci.yml
  pkg/configuration/config.go
  pkg/configuration/config_test.go
  pkg/handler/auth.go
  pkg/handler/config.go
  pkg/handler/datasources.go
  pkg/model/config.go
  pkg/model/dashboard.go
  pkg/model/datasource.go
  pkg/model/user.go
  pkg/query/querier.go
  pkg/server.go
  pkg/store/dashboard_store.go
  pkg/store/datasource_store.go
  pkg/store/datasource_store_test.go
  pkg/store/user_store.go
Labels: size/L, refactoring

#35 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, size/L

#34 remote_store + mock prometheus + test
  .gitignore
  main.go
  pkg/handler/api_error.go
  pkg/handler/datasources.go
  pkg/handler/handle_spa.go
  pkg/handler/handler.go
  pkg/handler/handler_test.go
  pkg/handler/init_test.go
  pkg/handler/lethe.go
  pkg/handler/prometheus.go
  pkg/handler/remote.go
  pkg/handler/remote_test.go
  pkg/handler/router.go
  pkg/handler/router_test.go
  pkg/mock/prometheus.go
  pkg/mock/prometheus_test.go
  pkg/query/querier.go
  pkg/query/query.go
  pkg/server.go
  pkg/store/alert_rule_store_test.go
  pkg/store/datasource_store.go
  pkg/store/remote_store.go
  pkg/store/remote_store_test.go
  pkg/store/store.go
Labels: enhancement, size/XXL, refactoring, test

#43 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: size/M

#44 Update issue templates
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: size/S

#38 From 29 branch without koreanlang
  go.mod
  go.sum
  pkg/handler/init_test.go
  pkg/store/datasource_store.go
  pkg/store/datasource_store_test.go
  pkg/store/discovery/discovery.go
  pkg/store/discovery/kubernetes/kubernetes.go
  pkg/store/discovery/kubernetes/kubernetes_test.go
  pkg/store/store.go
Labels: size/L

#53 52 goimports
  .github/workflows/pull-request.yml
  .gitignore
  Dockerfile
  Makefile
  go.mod
  go.sum
  hack/checks.sh
  hack/go-licenses.sh
  hack/list_users.sh
  hack/test-cover.sh
  main.go
  pkg/handler/api_error.go
  pkg/handler/auth.go
  pkg/handler/config.go
  pkg/handler/datasources.go
  pkg/handler/handler_test.go
  pkg/handler/init_test.go
  pkg/handler/remote.go
  pkg/handler/remote_test.go
  pkg/handler/router_test.go
  pkg/mock/prometheus_test.go
  pkg/store/datasource_store.go
  pkg/store/datasource_store_test.go
  pkg/store/discovery/kubernetes/kubernetes.go
  pkg/store/discovery/kubernetes/kubernetes_test.go
  pkg/store/remote_store.go
  pkg/store/remote_store_test.go
  pkg/store/user_store.go
Labels: size/XL, refactoring

#55 47 multi datasource alert
  .github/workflows/pull-request.yml
  Makefile
  etc/alerting.tbd.yml
  etc/alertrules/sample.yaml
  etc/datasources.dev.yaml
  go.mod
  go.sum
  hack/test-failfast.sh
  main.go
  pkg/alert/alert.go
  pkg/alerter/alerter.go
  pkg/alerter/alerter_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/configuration/config.go
  pkg/configuration/config_test.go
  pkg/handler/datasource.go
  pkg/handler/init_test.go
  pkg/handler/router.go
  pkg/mock/alert_rule_file.go
  pkg/mock/alertmanager.go
  pkg/mock/datasource.go
  pkg/mock/datasource_config.go
  pkg/mock/prometheus.go
  pkg/mock/prometheus_test.go
  pkg/model/config.go
  pkg/model/datasource.go
  pkg/model/rulefmt.go
  pkg/store/alert_rule_store.go
  pkg/store/alert_rule_store_test.go
  pkg/store/dashboard_store.go
  pkg/store/datasource_store.go
  pkg/store/datasource_store_test.go
  pkg/store/remote_store.go
  pkg/store/remote_store_test.go
  pkg/store/store.go
  pkg/store/user_store.go
Labels: enhancement, size/XXL

#57 logger package using logrus
  go.mod
  go.sum
  main.go
Labels: size/S, technical debt

#59 alerter & mock servers
  .github/workflows/pull-request.yml
  Makefile
  etc/alertrules/sample.yaml
  go.mod
  go.sum
  hack/test-failfast.sh
  main.go
  main_test.go
  pkg/alerter/alerter.go
  pkg/alerter/alerter_test.go
  pkg/handler/alert.go
  pkg/handler/datasource.go
  pkg/handler/init_test.go
  pkg/handler/remote.go
  pkg/handler/remote_test.go
  pkg/mock/alert_rule_file.go
  pkg/mock/alertmanager.go
  pkg/mock/prometheus.go
  pkg/mock/prometheus_test.go
  pkg/mock/servers/servers.go
  pkg/mock/servers/servers_test.go
  pkg/mocker/alertmanager/alertmanager.go
  pkg/mocker/alertmanager/alertmanager_test.go
  pkg/mocker/client/client.go
  pkg/mocker/client/client_test.go
  pkg/mocker/context.go
  pkg/mocker/lethe/lethe.go
  pkg/mocker/lethe/lethe_test.go
  pkg/mocker/mocker.go
  pkg/mocker/mocker_test.go
  pkg/mocker/prometheus/prometheus.go
  pkg/mocker/prometheus/prometheus_test.go
  pkg/store/alert_rule_store_test.go
  pkg/store/alertrule/alertrule.go
  pkg/store/alertrule/alertrule_test.go
  pkg/store/remote/remote.go
  pkg/store/remote/remote_test.go
  pkg/store/remote_store_test.go
  pkg/store/store.go
Labels: size/XXL, test

#60 Update pull-request.yml
  .github/workflows/pull-request.yml
Labels: size/S
