Repository kuoss/venti, pull requests merged in 2023-06, with the labels that each got.

#75 rename store to service
  main.go
  pkg/alerter/alerter.go
  pkg/alerter/alerter_test.go
  pkg/handler/alert.go
  pkg/handler/auth.go
  pkg/handler/dashboard.go
  pkg/handler/datasource.go
  pkg/handler/handler.go
  pkg/handler/handler_test.go
  pkg/handler/remote/remote.go
  pkg/handler/remote/remote_test.go
  pkg/handler/router.go
  pkg/handler/router_test.go
  pkg/handler/status.go
  pkg/handler/status_test.go
  pkg/service/alerting/alerting.go
  pkg/service/alerting/alerting_test.go
  pkg/service/alertrule/alertrule.go
  pkg/service/alertrule/alertrule_test.go
  pkg/service/dashboard/dashboard.go
  pkg/service/dashboard/dashboard_test.go
  pkg/service/datasource/datasource.go
  pkg/service/datasource/datasource_test.go
  pkg/service/discovery/discovery.go
  pkg/service/discovery/kubernetes/kubernetes.go
  pkg/service/discovery/kubernetes/kubernetes_test.go
  pkg/service/remote/remote.go
  pkg/service/remote/remote_test.go
  pkg/service/service.go
  pkg/service/service_test.go
  pkg/service/status/status.go
  pkg/service/status/status_test.go
  pkg/service/user/user.go
  pkg/service/user/user_test.go
  pkg/store/store.go
Labels: size/XL, refactoring

#79 Add token middleware
  pkg/handler/middleware.go
  pkg/handler/middleware_test.go
  pkg/handler/router.go
Labels: enhancement, size/M

#82 bugfix on datasource page for unhealthy datasource
  Makefile
  etc/dashboards/sample.yml
  hack/dev.sh
  pkg/service/dashboard/dashboard_test.go
  web/src/stores/datasource.js
Labels: bug, size/M, test

#84 optional channing for severity
  web/src/views/AlertView.vue
Labels: size/XS
